# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff13c17f2e6c983cfefca928979618aa01ea6b0e7940e5aeb6e153f5fd68fa62562c1ab38f09d3269653ba068f12f478f46c6aab673ee22b90324bb99d57b09

test:
  secret_key_base: 8331d5a3f9908824938d4a449425b769f1dabd76762432f881f524d9018fa08fe4bd756fb0817bafd52de3578ad510df7d00f75ba9f33ecee7ecee1ee9b8c9a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
